### ISSUE TITLE
Warema slat position state and slat position up/down separate switch

### ISSUE THREAD

**Issue by pnamenyi** [Taraman17/hass-homee#64] opened 2024-04-01 22:44 UTC
First: thanks for this integration, it works fine! I have a Warema cube, Warema covers and they report "slat position" to homee. All other measurements (state, position, slat rotation (impulse)) from homee are linked to HA, except this one. 
I would appreciate being able to see and set the slat position in HA and have separate UP/DOWN slat rotation impulse switches. It would be great to make shade based on automation during the day.
Thanks in advance!

**Comment by Taraman17** [comment] 2024-04-15 11:10
Hi,
can you provide logs as laid our here: https://github.com/Taraman17/hass-homee#homee-device-not-working-correctly

**Comment by Taraman17** [comment] 2024-05-11 10:10
Hi, a little heads up for the logs...

**Comment by stefankns** [comment] 2024-05-14 17:17
Hi, I did not create the issue but I am facing the some challenge with my „Warema Raffstore“ devices. So I might jump in with - hopefully the right - logs.
The first line is the Warema Raffstore device, the second line is the associated remote device. I hope this might help.

2024-05-14 18:48:06.116 INFO (MainThread) [custom_components.homee] Found node Raffstore Wohnzimmer Festverglasung, with following Data: {'id': 30, 'name': 'Raffstore%20Wohnzimmer%20Festverglasung', 'profile': 2002, 'image': 'default', 'favorite': 0, 'order': 28, 'protocol': 23, 'routing': 0, 'state': 1, 'state_changed': [1715667989](tel:1715667989), 'added': [1615396155](tel:1615396155), 'history': 1, 'cube_type': 14, 'note': 'WAREMA%20ZwischenStecker%20%281106448%29', 'services': 7, 'phonetic_name': '', 'owner': 2, 'security': 0, 'attributes': [{'id': 145, 'node_id': 30, 'instance': 0, 'minimum': 0, 'maximum': 4, 'current_value': 1.0, 'target_value': 1.0, 'last_value': 1.0, 'unit': 'n%2Fa', 'step_value': 1.0, 'editable': 1, 'type': 135, 'state': 1, 'last_changed': [1715703922](tel:1715703922), 'changed_by': 1, 'changed_by_id': 0, 'based_on': 1, 'data': '', 'name': '', 'options': {'can_observe': [300], 'observes': [158], 'automations': ['toggle']}}, {'id': 146, 'node_id': 30, 'instance': 0, 'minimum': 0, 'maximum': 100, 'current_value': 100.0, 'target_value': 100.0, 'last_value': 100.0, 'unit': '%25', 'step_value': 0.5, 'editable': 1, 'type': 15, 'state': 1, 'last_changed': [1715703922](tel:1715703922), 'changed_by': 1, 'changed_by_id': 0, 'based_on': 1, 'data': '', 'name': '', 'options': {'automations': ['step'], 'history': {'day': 35, 'week': 5, 'month': 1}}}, {'id': 147, 'node_id': 30, 'instance': 0, 'minimum': 4, 'maximum': 240, 'current_value': 57.0, 'target_value': 57.0, 'last_value': 90.0, 'unit': 's', 'step_value': 1.0, 'editable': 1, 'type': 110, 'state': 1, 'last_changed': [1615396246](tel:1615396246), 'changed_by': 1, 'changed_by_id': 0, 'based_on': 1, 'data': '', 'name': ''}, {'id': 148, 'node_id': 30, 'instance': 0, 'minimum': 4, 'maximum': 240, 'current_value': 57.0, 'target_value': 57.0, 'last_value': 90.0, 'unit': 's', 'step_value': 1.0, 'editable': 1, 'type': 111, 'state': 1, 'last_changed': [1615396252](tel:1615396252), 'changed_by': 1, 'changed_by_id': 0, 'based_on': 1, 'data': '', 'name': ''}, {'id': 149, 'node_id': 30, 'instance': 0, 'minimum': 0, 'maximum': 1, 'current_value': 0.0, 'target_value': 0.0, 'last_value': 0.0, 'unit': 'n%2Fa', 'step_value': 1.0, 'editable': 1, 'type': 324, 'state': 1, 'last_changed': [1615396155](tel:1615396155), 'changed_by': 1, 'changed_by_id': 0, 'based_on': 1, 'data': '', 'name': ''}, {'id': 150, 'node_id': 30, 'instance': 0, 'minimum': -75, 'maximum': 75, 'current_value': -25.0, 'target_value': -25.0, 'last_value': -25.0, 'unit': '%C2%B0', 'step_value': 1.0, 'editable': 1, 'type': 113, 'state': 1, 'last_changed': [1715703922](tel:1715703922), 'changed_by': 1, 'changed_by_id': 0, 'based_on': 1, 'data': '', 'name': '', 'options': {'automations': ['step']}}, {'id': 151, 'node_id': 30, 'instance': 0, 'minimum': 0, 'maximum': 24, 'current_value': 1.6, 'target_value': 1.6, 'last_value': 0.0, 'unit': 's', 'step_value': 0.1, 'editable': 1, 'type': 114, 'state': 1, 'last_changed': [1615396156](tel:1615396156), 'changed_by': 1, 'changed_by_id': 0, 'based_on': 1, 'data': '', 'name': ''}, {'id': 152, 'node_id': 30, 'instance': 0, 'minimum': -127, 'maximum': 127, 'current_value': -75.0, 'target_value': -75.0, 'last_value': 0.0, 'unit': '%C2%B0', 'step_value': 1.0, 'editable': 1, 'type': 322, 'state': 1, 'last_changed': [1615396156](tel:1615396156), 'changed_by': 1, 'changed_by_id': 0, 'based_on': 1, 'data': '', 'name': ''}, {'id': 153, 'node_id': 30, 'instance': 0, 'minimum': -127, 'maximum': 127, 'current_value': 75.0, 'target_value': 75.0, 'last_value': 0.0, 'unit': '%C2%B0', 'step_value': 1.0, 'editable': 1, 'type': 323, 'state': 1, 'last_changed': [1615396156](tel:1615396156), 'changed_by': 1, 'changed_by_id': 0, 'based_on': 1, 'data': '', 'name': ''}, {'id': 154, 'node_id': 30, 'instance': 0, 'minimum': 1, 'maximum': 20, 'current_value': 6.0, 'target_value': 6.0, 'last_value': 0.0, 'unit': 'n%2Fa', 'step_value': 1.0, 'editable': 1, 'type': 174, 'state': 1, 'last_changed': [1615396156](tel:1615396156), 'changed_by': 1, 'changed_by_id': 0, 'based_on': 1, 'data': '', 'name': ''}, {'id': 155, 'node_id': 30, 'instance': 0, 'minimum': 0, 'maximum': 2, 'current_value': 0.0, 'target_value': 0.0, 'last_value': 1.0, 'unit': 'n%2Fa', 'step_value': 1.0, 'editable': 1, 'type': 337, 'state': 1, 'last_changed': [1713470190](tel:1713470190), 'changed_by': 1, 'changed_by_id': 0, 'based_on': 1, 'data': '', 'name': ''}, {'id': 156, 'node_id': 30, 'instance': 0, 'minimum': 0, 'maximum': 0, 'current_value': 0.0, 'target_value': 0.0, 'last_value': 0.0, 'unit': 'text', 'step_value': 1.0, 'editable': 0, 'type': 45, 'state': 1, 'last_changed': [1615396156](tel:1615396156), 'changed_by': 1, 'changed_by_id': 0, 'based_on': 1, 'data': '[05930141007](tel:05930141007)', 'name': ''}, {'id': 157, 'node_id': 30, 'instance': 0, 'minimum': 0, 'maximum': 1, 'current_value': 0.0, 'target_value': 0.0, 'last_value': 0.0, 'unit': 'n%2Fa', 'step_value': 1.0, 'editable': 1, 'type': 170, 'state': 1, 'last_changed': [1615396156](tel:1615396156), 'changed_by': 1, 'changed_by_id': 0, 'based_on': 1, 'data': '', 'name': ''}, {'id': 186, 'node_id': 30, 'instance': 0, 'minimum': 0, 'maximum': 100, 'current_value': 100.0, 'target_value': 100.0, 'last_value': 100.0, 'unit': '%25', 'step_value': 0.5, 'editable': 1, 'type': 349, 'state': 1, 'last_changed': [1624446307](tel:1624446307), 'changed_by': 1, 'changed_by_id': 0, 'based_on': 1, 'data': '', 'name': ''}, {'id': 189, 'node_id': 30, 'instance': 0, 'minimum': -75, 'maximum': 75, 'current_value': 38.0, 'target_value': 38.0, 'last_value': 38.0, 'unit': '%C2%B0', 'step_value': 1.0, 'editable': 1, 'type': 350, 'state': 1, 'last_changed': [1624446307](tel:1624446307), 'changed_by': 1, 'changed_by_id': 0, 'based_on': 1, 'data': '', 'name': ''}, {'id': 200, 'node_id': 30, 'instance': 0, 'minimum': 5, 'maximum': 45, 'current_value': 30.0, 'target_value': 30.0, 'last_value': 0.0, 'unit': 'min', 'step_value': 5.0, 'editable': 1, 'type': 88, 'state': 1, 'last_changed': 0, 'changed_by': 0, 'changed_by_id': 0, 'based_on': 8, 'data': '', 'name': ''}, {'id': 235, 'node_id': 30, 'instance': 0, 'minimum': 0, 'maximum': 1, 'current_value': 1.0, 'target_value': 1.0, 'last_value': 0.0, 'unit': '', 'step_value': 1.0, 'editable': 1, 'type': 385, 'state': 1, 'last_changed': 0, 'changed_by': 0, 'changed_by_id': 0, 'based_on': 0, 'data': '', 'name': ''}]}
2024-05-14 18:48:06.116 INFO (MainThread) [custom_components.homee] Found node Wandsender Wohnzimmer Festverglasung, with following Data: {'id': 31, 'name': 'Wandsender%20Wohnzimmer%20Festverglasung', 'profile': 41, 'image': 'default', 'favorite': 0, 'order': 29, 'protocol': 23, 'routing': 0, 'state': 1, 'state_changed': [1715356788](tel:1715356788), 'added': [1615396304](tel:1615396304), 'history': 1, 'cube_type': 14, 'note': 'WAREMA%20Wandsender%20basic%20%281012296%29', 'services': 0, 'phonetic_name': '', 'owner': 2, 'security': 0, 'attributes': [{'id': 158, 'node_id': 31, 'instance': 0, 'minimum': 0, 'maximum': 9, 'current_value': 0.0, 'target_value': 0.0, 'last_value': 2.0, 'unit': 'n%2Fa', 'step_value': 1.0, 'editable': 0, 'type': 300, 'state': 1, 'last_changed': [1713470190](tel:1713470190), 'changed_by': 1, 'changed_by_id': 0, 'based_on': 1, 'data': '', 'name': '', 'options': {'observed_by': [145]}}, {'id': 159, 'node_id': 31, 'instance': 0, 'minimum': 0, 'maximum': 0, 'current_value': 0.0, 'target_value': 0.0, 'last_value': 0.0, 'unit': 'text', 'step_value': 1.0, 'editable': 0, 'type': 45, 'state': 1, 'last_changed': [1615396304](tel:1615396304), 'changed_by': 1, 'changed_by_id': 0, 'based_on': 1, 'data': '[07319121012](tel:07319121012)', 'name': ''}, {'id': 160, 'node_id': 31, 'instance': 0, 'minimum': 0, 'maximum': 1, 'current_value': 0.0, 'target_value': 0.0, 'last_value': 0.0, 'unit': 'n%2Fa', 'step_value': 1.0, 'editable': 1, 'type': 170, 'state': 1, 'last_changed': [1621765009](tel:1621765009), 'changed_by': 1, 'changed_by_id': 0, 'based_on': 1, 'data': '', 'name': ''}, {'id': 236, 'node_id': 31, 'instance': 0, 'minimum': 0, 'maximum': 1, 'current_value': 1.0, 'target_value': 1.0, 'last_value': 0.0, 'unit': '', 'step_value': 1.0, 'editable': 1, 'type': 385, 'state': 1, 'last_changed': 0, 'changed_by': 0, 'changed_by_id': 0, 'based_on': 0, 'data': '', 'name': ''}]}

And thanks for the great work. I just installed the integration some days ago and it is already doing a perfect job on many devices.

**Comment by Taraman17** [comment] 2024-05-15 12:42
Thank you,
That is exactly what I need - I see some testing coming up for you. ;-)

**Comment by Taraman17** [comment] 2024-05-15 13:01
https://github.com/Taraman17/hass-homee/wiki/WAREMA-WMS-Zwischenstecker

**Comment by stefankns** [comment] 2024-05-15 18:11
Klar, kein Problem. Wusste nur nicht genau, was alles hilfreich ist.
![IMG_0906](https://github.com/Taraman17/hass-homee/assets/91949743/f48dbf12-22c7-432e-88c5-dc1e0a0e996d)
![IMG_0907](https://github.com/Taraman17/hass-homee/assets/91949743/f1e985ee-8512-4c62-adfc-1e9e6ec82242)

Soll ich für den Wandsender einen neuen Issue aufmachen? Ist dann doch ne separate Baustelle. Weiß auch nicht, ob und wie der aktuell schon integriert werden könnte. Ist ja ein „Remote“ Device, so taucht er auch schon als Gerät in HA auf. Aber eben ohne Controls, Sensoren oder ähnliches.

Freue mich aufs Testen :-)

**Comment by Taraman17** [comment] 2024-05-16 09:29
OK, since the creator of this issue seems to be english-speaking, I return to that language. ;-)

Thanks for the pictures. Are there any configuration options? I got SLAT_MIN_ANGLE, SLAT_MX_ANGLE, SLAT_STEPS, DOWN_POSITION, DOWN_SLAT_POSITION, MOTOR_ROTATION in the data, that Homee is providing

**Comment by stefankns** [comment] 2024-05-16 12:47
You are right. Let’s stick to English.

Sorry, that I missed the config part. I can provide the following:
![IMG_0911](https://github.com/Taraman17/hass-homee/assets/91949743/9a8894aa-8da2-45fb-851e-9456abfe28f2)

The following are screenshots from the sub-menus:
![IMG_0912](https://github.com/Taraman17/hass-homee/assets/91949743/5b0c29c9-17f3-4bab-bdd6-d484651a18ca)
![IMG_0913](https://github.com/Taraman17/hass-homee/assets/91949743/44df2850-99fb-48af-9db3-2665923bb232)
![IMG_0914](https://github.com/Taraman17/hass-homee/assets/91949743/94867270-274e-4eac-b696-00f7eb544a9e)
![IMG_0915](https://github.com/Taraman17/hass-homee/assets/91949743/c57bdade-7483-4bce-b190-a9af08c01701)
![IMG_0916](https://github.com/Taraman17/hass-homee/assets/91949743/16ebb9ec-f522-4056-8f52-d31456fbf6ad)
![IMG_0917](https://github.com/Taraman17/hass-homee/assets/91949743/4e8e25b3-596b-4e09-9190-cb594a77b651)
![IMG_0918](https://github.com/Taraman17/hass-homee/assets/91949743/69f8cd81-707d-48e1-8855-3ab27ca60a23)
![IMG_0919](https://github.com/Taraman17/hass-homee/assets/91949743/c91f7111-7913-4e77-9090-dbd8a1f1c708)

So it looks like the options you mentioned seem to be there.
The switch „Erkennungsmodus“ wiggles the slats shortly and is deactivated automatically afterwards.

**Comment by Taraman17** [comment] 2024-05-16 14:21
Great, thank you so much.
Do the times for moving up/sown or turning completely affect the speed at which the slats move if you change it? Is there any sense in changing these or is it in fact more a sensor that can be adjusted for some reason?

**Comment by stefankns** [comment] 2024-05-16 14:53
The times for moving up and down make definitely sense to be configurable as a control. My understanding is, that if an up or down command is issued, the „Zwischenstecker“ (the cover itself is just a motor, completely stupid) tries to power the motor for that time. There are end switches implemented in the cover, so that the motor turns off at the end of the physical movement range, but it is also used to calibrate the end positions. The Zwischenstecker assumes a 0 or 100% based on reaching the endpoint by powering the motor for the adjusted times. So the procedure to adjust these values is to measure the up and down times for a device with a clock and add about 2s. If you, for example, move up and down a lot without hitting the end points, the real position may differ quite a lot from the „assumed“ feedback position of the Zwischenstecker (again: there is no position encoder in the device, the logic is quite primitive). I guess, that even the „go to position X (in %)“ is just calculated by these configured times and converted into run-times to power the motor.
So to make things short, a proper adjusted of these values is important from my point of view. Someone else might know better, but this is how I reverse engineered the settings here.

**Comment by Taraman17** [comment] 2024-05-20 17:53
OK, I just released a Beta, that has support for slat-covers.

Please pay special attention on the open/close/openein/closing state in cover UI and State-sensor.

Can you please check, if the "Orientierung Umkehren" switch in Homee corresponds to the "Motor Drehrichtung" Switch in HA. If so, the logic for reacting to this is not implemented and open/close will most likely be reversed.

**Comment by stefankns** [comment] 2024-05-21 17:31
Thanks a lot!
First of all: great job! I am impressed how you can get that far without beeing able to test everything with the devices.

**Feedback Covers ("Rolladen via Zwischenstecker")**
Cool, that you also updated the covers according to the full profile. I checked the "Motor Drehrichtung" and it corresponds to "Orientierung umkehren" and I can see the changes made in HA in the Homee App. I also changed "Dauer Hochfahren", "Dauer "Runterfahren", Polling "Intervall" and "Untere Position". All are in sync and can be updated in either HA or the Homee App. Control of the device is normal and as expected. The status feedback for open/opening/closing/closed is fully correct (when "Motor Drehrichtung" is set matching to the motor).

**Feedback Slat Covers ("Raffstore via Zwischenstecker")**
Here I also tested all options. They are in sync and work properly (both directions HA <-> Homee). The open/opening/closing/closed did not work before but is working with the new implementation. After installing the beta, control of the device worked flawless at first. Up, down, set position, set tilt position. Several times in a row. But suddenly things got kind of weird and out of sync (hard to explain and reproduce). I suddenly had a -128° tilt position for the slats in Homee (for a -75° to 75° setup), HA controls did not work at all for some time. Moving the tilt position slider in different tilt positions finally even led to the slat moving up and down in position instead of tilting. Maybe it was caused by tilting while still moving. As I said, hard to replicate the error. I restarted HA, moved the slat to fully open and everything was back to normal and working properly. Maybe there are some difficulties, when a lot of things happen at the same time. As mentioned before, I have implemented a simple Node-RED Homee API based communication with the Warema devices. Here I noticed, how "laggy" the response of the Warema cube or system is, meaning position updates or tilt position updates drop in with sometimes up to 15s delay (at least with the Node-RED API block). I will try to give better feedback when I understand better, what is triggering the strange behavior.

One proposal for additional controls:
In the Homee App there are two buttons for "Lamellenrotation (Impuls)" (open and close). They are implemented in the way, that the full rotation range ("Maximaler Lamellenwinkel" - "Minimaler Lamellenwinkel") is divided by "Lamellenstufen" (in the example data 6) and the tilt angle is updated in opening or closing direction by that value. I guess this is why they call it pulse.  I do not know if there is a control command for that, or if it is calculated and set manually. But I guess there might be a control command, which is why there is the parameter "Lamellenstufen".
I think it would be perfect to implement it as two "button entities" in HA as well and trigger that respective command. That is, by the way, what you would do, when for example pressing the up or down button on the remote (Wandsender). One short press up means tilt "one step", long-press means move it up instead. The open and close control button for tilt in HA for the slat covers is actually tilting it fully inwards or fully outwards right now. I do not know how other devices are implemented here normally. If it is a step or full tilt. Concerning the up and down buttons here, which are triggering a full move up or move down command, this is the same logic, but maybe it does not make sense for a slat cover of that kind. For this device, both fully inward tilting or fully outward tilting are still fully closed.

Again, great work. Looking forward to using it and testing it more.

**Comment by juergjue** [comment] 2024-05-21 18:12
Hi, I have tried today the new beta1 on my covers and slat roof. It all works as expected.
Thanks for that and great job!

**Comment by stefankns** [comment] 2024-05-22 15:58
Thanks for your answer. I thought I tested the popup control and that it was fully tilting the slats with one button push. I tested again now and your are right, it just triggers one impuls and this corresponds to one step. So I am good, this is exactly the implementation I hoped for. I will be able to trigger the tilt pulses now based on the buttons on the Warema remote using the tilt services.

I will keep you posted on the strange behavior. It did not happen again yet. I will add the debugging to be able to monitor it. The transformation of the 0 to 100 to -75 to 75 was exactly what I was thinking about, because the tilt was showing -128 during the process. A "late value" might cause trouble here. I am really happy with the new device support, I can already decommission 90% of my Node-RED "driver" for the Warema components now. Fingers crossed for the Warema Wandsender basic :-)

But I have one more question:
When the covers are moving and a tilt command is issued, do you actively stop the movement, before you send the tilt command, or is that behavior coming out of the HA part of the cover implementation?

**Comment by Taraman17** [comment] 2024-05-22 18:10
Hey, great it already works that good!
No, I don't stop the covers on a tilt command. This might be a HA behavior. Maybe you can spot what happens with the debug logging.

**Comment by Taraman17** [comment] 2024-06-01 21:14
Fixed with Release 2.9.4

**Closed by Taraman17** 2024-06-01 21:14 UTC
Labels: enhancement, released on @beta
