### ISSUE TITLE
AEON Labs ZW062 Garage Door Controller not working correctly

### ISSUE THREAD

**Issue by Hoss0305** [Taraman17/hass-homee#98] opened 2024-08-04 16:21 UTC
Hello, 
I recently switched my SmartHome to Home Assistant and connected it to my Homee via HACS. Everything worked. The devices were found and integrated in HA. However, one device (AEON Labs ZW062 Garage Door Controller) cannot be operated. The sensor data is displayed correctly. 
Example: The functions are open gate, stop gate and close gate. When the gate is closed, only the open gate and gate STOP buttons are displayed; when the gate is open, only close gate and gate STOP are displayed. The problem now is that when the gate is closed, close gate and gate STOP are displayed, although gate STOP doesn't work either. When the gate is open, the displays are the same, but there is no function here either. I have attached a log extract to this problem description. 
It would be great if someone could help me with this and give me assistance.

[2024-08-04 163428.579 WARNING (Sync.txt](https://github.com/user-attachments/files/16488237/2024-08-04.163428.579.WARNING.Sync.txt)

**Comment by Taraman17** [comment] 2024-08-25 21:16
Hi,
this sounds, like the controls are reversed, or the position sensing is reversed.
To fix this, please attach a log excerpt as laid out here:
https://github.com/Taraman17/hass-homee?tab=readme-ov-file#homee-device-not-working-correctly

The warnings in the log you attached are not related to this issue and the cause will be fixed in the next release.

**Comment by Hoss0305** [comment] 2024-08-26 05:25
Hello,
here is the configuration.yaml excerpt from the AEON Labs ZW062 Garage Door Controller regarding my previously described problem with the apparently swapped controls. It would be nice if there could be a solution to this
Best wishes Hoss0305

[configuration_yaml_homee.txt](https://github.com/user-attachments/files/16744373/configuration_yaml_homee.txt)

**Comment by Taraman17** [comment] 2024-08-26 11:05
https://github.com/Taraman17/hass-homee/wiki/AEON-Labs-ZW062-Garage-Door-Controller

I will take a look at it.

**Comment by Taraman17** [comment] 2024-08-26 11:43
So, after some Research, I found out, that the Controller only seems to supports a single command for open/close/stop.
Is that correct?
What controls do you have in the Homee app?

It seems, that this will not be an easy fix and we might have to do some testing on your side.

**Comment by Hoss0305** [comment] 2024-08-26 12:24
Hello,
I can't say how many commands the controller supports for opening/closing/stopping. 
If I operate the controller via ioBroker, I get 5 values (UpDown-74) back from the controller (0=open/1=closed/2=fault/3=opens/4=closes), 
![ioBroker-Screenshot Homee-Controller](https://github.com/user-attachments/assets/5fdebddf-1a84-46ef-baa5-f5dbe3e0f969)
which the Homee app also shows as the status. I have the Up, Stop and Down buttons to operate the app and the Windows UI. 
I hope this information helps.
Regards Hoss0305

**Comment by Taraman17** [comment] 2024-08-26 12:50
Yes, that helps already.
The garage door shows one more value than the other shutter controllers I saw so far.
The others only have 0-3, without the fault status.

I'll have to see, how I can incorporate that.
Thanks for the info.

**Comment by Taraman17** [comment] 2024-08-30 20:27
As it turns out, I was wrong. 5 Stati for the up_down state are common for covers.
I just had a bug that for covers without position indication, the open/closed logic was reversed.

One thing however I'm not able to fix for now ist that on the other covers so far, status "2" is "partially open" and for yours it is "fault". I don't want to change the status there to "partially open/fault", since it might alarm people for no reason.

See [howto Beta](https://github.com/Taraman17/hass-homee/blob/master/howto_beta.md) on how to test it.

**Comment by Hoss0305** [comment] 2024-09-03 06:10
Hello,
I have installed the beta and it looks good so far. So far I have not been able to find any errors. Everything is currently working as it should, but I will continue to monitor everything and then give feedback. Thank you very much

**Comment by Taraman17** [comment] 2024-09-24 11:20
Fixed with release 2.9.6

**Closed by Taraman17** 2024-09-24 11:20 UTC
Labels: bug, released on @beta
